{-|
Module: IHP.Router.Trie
Description: Path-indexed trie for fast URL dispatch

A 'RouteTrie' is the runtime data structure used by IHP's router to dispatch
incoming requests to handlers. Paths are split on @/@ and walked segment-by-segment.
At each node, literal matches are tried first, then a typed capture, then a
splat fall-through. Handlers at a leaf are indexed by HTTP method so the same
path can dispatch to different actions for GET / POST / PATCH / etc.

The trie is built once at application startup and shared across all
requests; lookup is a single linear walk with no backtracking.
-}
module IHP.Router.Trie
    ( RouteTrie (..)
    , CaptureSpec (..)
    , PatternSegment (..)
    , HandlersByMethod
    , WaiHandler
    , Captures
    , LookupResult (..)
    , emptyTrie
    , insertRoute
    , insertRouteMethods
    , lookupTrie
    , mergeTrie
    , splitPath
    ) where

import Prelude
import Data.ByteString (ByteString)
import qualified Data.ByteString as ByteString
import qualified Data.ByteString.Char8 as ByteString.Char8
import Data.HashMap.Strict (HashMap)
import qualified Data.HashMap.Strict as HashMap
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import Network.HTTP.Types.Method (StdMethod)
import Network.Wai (Application)

-- | Captures collected while walking the trie, in path order. Each entry
-- is the raw bytestring the trie accepted for a @{name}@ or @{+name}@
-- segment. The handler at the leaf — generated by the TH splice — knows
-- each capture's Haskell type by position and calls 'parseCapture' to
-- extract the typed value.
--
-- Using a plain @[ByteString]@ (rather than a @HashMap Text Dynamic@)
-- avoids the @toDyn@/@fromDynamic@ round-trip and the @TypeRep@ equality
-- check on every request. The trade-off is that the ordering of the list
-- must match the order of captures in the path pattern, which the splice
-- takes care of.
type Captures = [ByteString]

-- | A WAI 'Application' that also receives the captures collected during
-- trie traversal.
type WaiHandler = Captures -> Application

-- | Per-method handlers at a trie leaf. Missing entries correspond to
-- @405 Method Not Allowed@. Backed by 'Map' (not 'HashMap') because
-- 'StdMethod' doesn't have a 'Hashable' instance and the per-node
-- cardinality is tiny (≤9 methods).
type HandlersByMethod = Map StdMethod WaiHandler

-- | Specification of a capture at a trie node.
--
-- A @{name}@ segment accepts any non-empty bytestring up to the next
-- @\/@; a @{+name}@ splat accepts the remainder of the path. Type-level
-- validation is not performed during the walk — it's the handler's job,
-- via 'parseCapture', once per request. This decouples URL matching from
-- parameter decoding and means each segment is parsed exactly once.
--
-- The 'captureName' is kept for debugging and error messages; the trie
-- itself doesn't use it.
newtype CaptureSpec = CaptureSpec
    { captureName :: Text
    }

-- | Path-indexed trie node.
--
-- Lookup priority at each node is: literal segment > typed capture > splat.
-- Splat captures consume the remaining path and land on the bundled
-- 'HandlersByMethod'.
data RouteTrie = RouteTrie
    { static   :: !(HashMap ByteString RouteTrie)
    , dynamic  :: !(Maybe (CaptureSpec, RouteTrie))
    , splat    :: !(Maybe (Text, HandlersByMethod))
    , handlers :: !HandlersByMethod
    }

-- | A single segment of a route pattern during trie construction.
data PatternSegment
    = LiteralSeg !ByteString
    | CaptureSeg !CaptureSpec
    | SplatSeg !Text

-- | Outcome of a trie lookup.
data LookupResult
    = Matched !WaiHandler !Captures
    | MethodNotAllowed ![StdMethod]
    | NotMatched

-- | An empty trie — matches nothing, has no handlers.
emptyTrie :: RouteTrie
emptyTrie = RouteTrie HashMap.empty Nothing Nothing Map.empty

-- | Split a path like @"/posts/123/edit"@ into @["posts","123","edit"]@.
-- Leading, trailing, and empty segments are dropped so @"/"@ and @""@ both
-- yield @[]@.
splitPath :: ByteString -> [ByteString]
splitPath = filter (not . ByteString.null) . ByteString.Char8.split '/'
{-# INLINE splitPath #-}

-- | Insert a route into the trie. Given a list of pattern segments, a
-- method, and a handler, this either extends the trie with new nodes or
-- merges into existing ones.
--
-- Inserting the same @(method, pattern)@ twice silently overrides.
insertRoute
    :: [PatternSegment]
    -> StdMethod
    -> WaiHandler
    -> RouteTrie
    -> RouteTrie
insertRoute pattern method = insertRouteMethods pattern [method]
{-# INLINE insertRoute #-}

-- | Like 'insertRoute' but registers the same handler under multiple
-- methods at once.
--
-- The TH splice uses this to implement @GET ⇒ GET+HEAD@ expansion
-- without emitting a duplicate handler lambda per method: one
-- 'WaiHandler' value, one trie walk, both methods registered at the
-- leaf.
insertRouteMethods
    :: [PatternSegment]
    -> [StdMethod]
    -> WaiHandler
    -> RouteTrie
    -> RouteTrie
insertRouteMethods [] methods handler trie =
    trie { handlers = foldr (\m h -> Map.insert m handler h) (handlers trie) methods }
insertRouteMethods (seg : rest) methods handler trie = case seg of
    LiteralSeg lit ->
        let child = HashMap.lookupDefault emptyTrie lit (static trie)
            child' = insertRouteMethods rest methods handler child
         in trie { static = HashMap.insert lit child' (static trie) }
    CaptureSeg spec ->
        let child = case dynamic trie of
                Just (_, existing) -> existing
                Nothing            -> emptyTrie
            child' = insertRouteMethods rest methods handler child
         in trie { dynamic = Just (spec, child') }
    SplatSeg name ->
        let existing = case splat trie of
                Just (_, h) -> h
                Nothing     -> Map.empty
         in trie { splat = Just (name, foldr (\m h -> Map.insert m handler h) existing methods) }

-- | Deep-merge two tries. Used at application startup to combine
-- fragments coming from separate controllers into one app-wide trie.
--
-- Right-biased: where both sides define a handler for the same method
-- at the same leaf, @b@ wins.
mergeTrie :: RouteTrie -> RouteTrie -> RouteTrie
mergeTrie a b = RouteTrie
    { static = HashMap.unionWith mergeTrie (static a) (static b)
    , dynamic = case (dynamic a, dynamic b) of
        (Nothing, x) -> x
        (x, Nothing) -> x
        (Just (_, aChild), Just (bSpec, bChild)) -> Just (bSpec, mergeTrie aChild bChild)
    , splat = case (splat a, splat b) of
        (Nothing, x) -> x
        (x, Nothing) -> x
        (Just (_, aH), Just (bName, bH)) -> Just (bName, Map.union bH aH)
    , handlers = Map.union (handlers b) (handlers a)
    }

-- | Look up a method+path pair in the trie.
--
-- Walks path segments with the priority order literal > typed capture > splat.
-- Returns 'Matched' with collected captures on success; if the path matches
-- a leaf but the method isn't registered, 'MethodNotAllowed' is returned
-- with the list of methods that do match. 'NotMatched' is returned when
-- no path walk reaches a leaf or splat.
lookupTrie :: RouteTrie -> StdMethod -> [ByteString] -> LookupResult
lookupTrie trie method = go trie []
  where
    -- 'captures' accumulates in REVERSE order during the walk for O(1)
    -- cons; reversed to path order before being handed to the handler.
    go node captures [] = case Map.lookup method (handlers node) of
        Just h  -> Matched h (reverse captures)
        Nothing
            | Map.null (handlers node) -> trySplatEmpty node captures
            | otherwise -> MethodNotAllowed (Map.keys (handlers node))

    go node captures (seg : rest) =
        case HashMap.lookup seg (static node) of
            Just child -> case go child captures rest of
                NotMatched -> tryCapture node captures seg rest
                other -> other
            Nothing -> tryCapture node captures seg rest

    tryCapture node captures seg rest = case dynamic node of
        Just (_spec, child) ->
            -- A single-segment capture accepts any non-empty segment.
            -- No type-level validation happens here; the handler at
            -- the leaf decodes the bytestring via 'parseCapture'.
            case go child (seg : captures) rest of
                NotMatched -> trySplat node captures (seg : rest)
                other      -> other
        Nothing -> trySplat node captures (seg : rest)

    trySplat node captures segs = case splat node of
        Just (_name, byMethod) ->
            let raw       = ByteString.intercalate "/" segs
                captures' = reverse (raw : captures)
             in case Map.lookup method byMethod of
                    Just h  -> Matched h captures'
                    Nothing
                        | Map.null byMethod -> NotMatched
                        | otherwise -> MethodNotAllowed (Map.keys byMethod)
        Nothing -> NotMatched

    trySplatEmpty node captures = case splat node of
        Just (_name, byMethod) ->
            let captures' = reverse ("" : captures)
             in case Map.lookup method byMethod of
                    Just h  -> Matched h captures'
                    Nothing
                        | Map.null byMethod -> NotMatched
                        | otherwise -> MethodNotAllowed (Map.keys byMethod)
        Nothing -> NotMatched
