{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}

{-|
Module: IHP.Router.TypedRoute
Description: Runtime support for typed GADT routes

This module contains the runtime support used by the IHP @[routes|...|]@
quasi-quoter for typed GADT actions. User code should declare typed routes with
the route DSL, not by building route records manually.
-}
module IHP.Router.TypedRoute
    ( HasActionMethods (..)
    , typedActionMethods
    , mkRouteParameterDoc
    , TypedRouteResponseHandler
    , mkTypedRouteResponseHandler
    , runTypedRouteAction
    , typedDocumentedRenderExpectationForResponse
    ) where

import Control.Monad (join)
import Data.Aeson qualified as JSON
import Data.Dynamic (fromDynamic)
import Data.OpenApi (ToSchema)
import Data.OpenApi.Schema.Validation qualified as SchemaValidation
import Data.Proxy (Proxy (..))
import Data.String.Conversions (cs)
import Data.Text (Text)
import Data.Typeable qualified as Typeable
import GHC.TypeLits (KnownSymbol, symbolVal)
import IHP.Controller.Render (renderHtmlOrJsonWithStatusCode)
import IHP.Controller.TypedAction (DecodeRequest (..), DecodedRequest, ParameterDoc (..), ParameterLocation (..), RenderTypedResponse, RequestDecodeError (..), TypedController, action, beforeAction)
import IHP.ControllerSupport (ControllerContext, InitControllerContext, Request, Respond, ResponseReceived, prepareRLSIfNeeded, respondAndExit, setupActionContext)
import IHP.ErrorController qualified as ErrorController
import IHP.RouterSupport
    ( DocumentedRenderExpectation (..)
    , attachOpenApiRenderExpectation
    )
import IHP.ViewSupport qualified as ViewSupport
import Network.HTTP.Types.Header (hContentType)
import Network.HTTP.Types.Method (StdMethod)
import Network.HTTP.Types.Status (Status, status500)
import Network.Wai (Application, responseLBS)
import Network.Wai.Middleware.EarlyReturn (earlyReturnMiddleware)
import Prelude

-- | Build the OpenAPI document for a path or query parameter declared by the
-- route DSL.
mkRouteParameterDoc ::
    forall field value.
    ( KnownSymbol field
    , Typeable.Typeable value
    , ToSchema value
    ) =>
    ParameterLocation ->
    Bool ->
    ParameterDoc
mkRouteParameterDoc location required =
    ParameterDoc
        { parameterName = cs (symbolVal (Proxy @field))
        , parameterLocation = location
        , parameterRequired = required
        , parameterSchema = Proxy @value
        , parameterTypeRep = Typeable.typeRep (Proxy @value)
        }
{-# INLINE mkRouteParameterDoc #-}

-- | Method lookup generated by the @[routes|...|] DSL for typed GADT actions.
class HasActionMethods action where
    actionMethods :: action -> Maybe [StdMethod]

-- | Returns the HTTP methods accepted by the generated route for an action
-- value. This is used by typed form helpers to choose the HTML form method and
-- method override field.
typedActionMethods :: forall action. (HasActionMethods action) => action -> Maybe [StdMethod]
typedActionMethods = actionMethods
{-# INLINE typedActionMethods #-}

data TypedRouteResponseHandler response where
    TypedRouteResponseHandler ::
        forall response view.
        (RenderTypedResponse view) =>
        { typedRouteResponseHandlerName :: Text
        , typedRouteResponseHandlerStatus :: Status
        , typedRouteResponseHandlerExpectation :: Maybe DocumentedRenderExpectation
        , typedRouteResponseHandlerMatch :: response -> Maybe view
        } ->
        TypedRouteResponseHandler response

mkTypedRouteResponseHandler ::
    forall response view.
    (RenderTypedResponse view) =>
    Text ->
    Status ->
    Maybe DocumentedRenderExpectation ->
    (response -> Maybe view) ->
    TypedRouteResponseHandler response
mkTypedRouteResponseHandler name status expectation match =
    TypedRouteResponseHandler
        { typedRouteResponseHandlerName = name
        , typedRouteResponseHandlerStatus = status
        , typedRouteResponseHandlerExpectation = expectation
        , typedRouteResponseHandlerMatch = match
        }
{-# INLINE mkTypedRouteResponseHandler #-}

runTypedRouteAction ::
    forall application controller body response.
    ( TypedController controller
    , DecodeRequest body
    , InitControllerContext application
    , ?application :: application
    , Typeable.Typeable application
    , Typeable.Typeable (controller body response)
    ) =>
    [TypedRouteResponseHandler response] ->
    controller body response ->
    Application
runTypedRouteAction responseHandlers typedAction waiRequest waiRespond =
    earlyReturnMiddleware
        ( \request respond -> do
            context <- setupActionContext @application (Typeable.typeOf typedAction) request respond
            let ?theAction = typedAction
            let ?context = context
            let ?respond = respond
            let ?request = context.request
            let ?modelContext = ?request.modelContext
            authenticatedModelContext <- prepareRLSIfNeeded ?modelContext
            let ?modelContext = authenticatedModelContext
            beforeAction @controller @body @response
            runTypedControllerAction @body @response responseHandlers (action typedAction)
        )
        waiRequest
        waiRespond
{-# INLINE runTypedRouteAction #-}

runTypedControllerAction ::
    forall body response.
    ( DecodeRequest body
    , ?context :: ControllerContext
    , ?request :: Request
    , ?respond :: Respond
    ) =>
    [TypedRouteResponseHandler response] ->
    (DecodedRequest body -> IO response) ->
    IO ResponseReceived
runTypedControllerAction responseHandlers runAction = do
    ErrorController.withRequestContext ?request do
        decodedBody <- decodeRequest @body
        case decodedBody of
            Left RequestDecodeError{requestDecodeErrorStatus, requestDecodeErrorMessage} ->
                respondAndExit (responseLBS requestDecodeErrorStatus [(hContentType, "text/plain")] (cs requestDecodeErrorMessage))
            Right typedBody ->
                runAction typedBody >>= renderTypedRouteResponse responseHandlers
{-# INLINE runTypedControllerAction #-}

renderTypedRouteResponse ::
    forall response.
    ( ?context :: ControllerContext
    , ?request :: Request
    , ?respond :: Respond
    ) =>
    [TypedRouteResponseHandler response] ->
    response ->
    IO ResponseReceived
renderTypedRouteResponse [] _ =
    respondAndExit (responseLBS status500 [(hContentType, "text/plain")] "Typed route response did not match any response metadata")
renderTypedRouteResponse (TypedRouteResponseHandler{typedRouteResponseHandlerStatus, typedRouteResponseHandlerExpectation, typedRouteResponseHandlerMatch} : rest) response =
    case typedRouteResponseHandlerMatch response of
        Nothing -> renderTypedRouteResponse rest response
        Just view -> do
            let currentRequest = ?request
            let ?request = attachOpenApiRenderExpectation typedRouteResponseHandlerExpectation currentRequest
            renderHtmlOrJsonWithStatusCode typedRouteResponseHandlerStatus view
{-# INLINE renderTypedRouteResponse #-}

typedDocumentedRenderExpectationForResponse ::
    forall response.
    ( Typeable.Typeable response
    , ViewSupport.JsonView response
    , JSON.ToJSON (ViewSupport.JsonResponse response)
    , ToSchema (ViewSupport.JsonResponse response)
    ) =>
    DocumentedRenderExpectation
typedDocumentedRenderExpectationForResponse =
    let response = Proxy @response
     in DocumentedRenderExpectation
        { expectedViewTypeName = cs (show (Typeable.typeRep response))
        , expectedTypedJson = fmap (JSON.toJSON . ViewSupport.json) . fromDynamic @response
        , expectedJsonSchemaValidationError = join . fmap (SchemaValidation.validatePrettyToJSON . ViewSupport.json) . fromDynamic @response
        }
{-# INLINE typedDocumentedRenderExpectationForResponse #-}
