{-|
Module: IHP.IDE.CodeGen.MigrationGenerator
Description: Generates database migration sql files
Copyright: (c) digitally induced GmbH, 2021
-}
module IHP.IDE.CodeGen.MigrationGenerator where

import IHP.Prelude
import qualified System.Directory as Directory
import qualified Data.Text as Text
import qualified Data.Text.Encoding as TextEncoding
import qualified Data.ByteString as ByteString
import qualified Data.Time.Clock.POSIX as POSIX
import qualified IHP.NameSupport as NameSupport
import qualified Data.Char as Char
import qualified Text.Read as Read
import qualified System.Process as Process
import qualified IHP.Postgres.Parser as Parser
import qualified IHP.SchemaCompiler.Parser as SchemaDesignerParser
import IHP.Postgres.Types
import Text.Megaparsec
import IHP.Postgres.Compiler (compileSql)
import IHP.IDE.CodeGen.Types
import qualified IHP.FrameworkConfig as FrameworkConfig
import Paths_ihp_ide (getDataFileName)

buildPlan :: Text -> Maybe Text -> IO (Int, [GeneratorAction])
buildPlan description sqlStatements = buildPlan' True description sqlStatements

buildPlanWithoutIHPSchema :: Text -> Maybe Text -> IO (Int, [GeneratorAction])
buildPlanWithoutIHPSchema description sqlStatements = buildPlan' False description sqlStatements

buildPlan' :: Bool -> Text -> Maybe Text -> IO (Int, [GeneratorAction])
buildPlan' includeIHPSchema description sqlStatements = do
    timestampRevision <- round <$> POSIX.getPOSIXTime
    revision <- nextAvailableMigrationRevision timestampRevision
    let slug = NameSupport.toSlug description

    migrationFiles <- case sqlStatements of
        Just sql -> pure (migrationFilesFromSql revision slug sql)
        Nothing -> do
            databaseUrl <- cs <$> FrameworkConfig.defaultDatabaseUrl
            appDiff <- diffAppDatabase includeIHPSchema databaseUrl
            pure (migrationFilesFromStatements revision slug appDiff)
    pure (revision,
            EnsureDirectory { directory = "Application/Migration" }
                : map (\(migrationFile, migrationSql) ->
                    CreateFile
                        { filePath = textToOsPath ("Application/Migration/" <> migrationFile)
                        , fileContent = migrationSql
                        }
                ) migrationFiles)

-- | Selects a revision that leaves room for a second migration generated by
-- the same plan and is newer than every existing migration.
nextAvailableMigrationRevision :: Int -> IO Int
nextAvailableMigrationRevision timestampRevision = do
    let migrationDirectory = "Application/Migration"
    directoryExists <- Directory.doesDirectoryExist migrationDirectory
    existingRevisions <- if directoryExists
        then mapMaybe migrationRevisionFromFileName <$> Directory.listDirectory migrationDirectory
        else pure []
    pure (nextMigrationRevision timestampRevision existingRevisions)

-- | Returns at least the timestamp revision and one more than the largest
-- existing revision.
nextMigrationRevision :: Int -> [Int] -> Int
nextMigrationRevision timestampRevision existingRevisions = case existingRevisions of
    [] -> timestampRevision
    _ -> max timestampRevision (maximum existingRevisions + 1)

-- | Reads the numeric revision prefix from a migration filename.
migrationRevisionFromFileName :: FilePath -> Maybe Int
migrationRevisionFromFileName fileName
    | not (".sql" `Text.isSuffixOf` cs fileName) = Nothing
    | otherwise = case takeWhile Char.isDigit fileName of
        [] -> Nothing
        revision -> Read.readMaybe revision

-- | Splits SQL submitted by the Schema Designer when it contains both
-- extension and regular statements. SQL that cannot be parsed, or does not
-- need splitting, is preserved byte-for-byte in a single migration.
migrationFilesFromSql :: Int -> Text -> Text -> [(Text, Text)]
migrationFilesFromSql revision slug sql =
    case Parser.parseSqlText sql of
        Right statements
            | any isCreateExtension statements
            , any isExecutableRegularStatement statements ->
                migrationFilesFromStatements revision slug statements
        _ -> [(migrationFileName revision slug, sql)]
    where
        isExecutableRegularStatement CreateExtension {} = False
        isExecutableRegularStatement Comment {} = False
        isExecutableRegularStatement _ = True

-- | Builds migration files from a schema diff. Extension statements are put
-- in a standalone migration so @ihp-migrate@ can execute only that migration
-- through the privileged database connection.
migrationFilesFromStatements :: Int -> Text -> [Statement] -> [(Text, Text)]
migrationFilesFromStatements revision slug statements =
    case (extensionStatements, regularStatements) of
        ([], []) -> [(migrationFileName revision slug, "-- Write your SQL migration code in here\n")]
        ([], regularStatements) -> [(migrationFileName revision slug, compileSql regularStatements)]
        (extensionStatements, []) -> [(migrationFileName revision slug, compileSql extensionStatements)]
        (extensionStatements, regularStatements) ->
            [ (migrationFileName revision "create-extensions", compileSql extensionStatements)
            , (migrationFileName (revision + 1) slug, compileSql regularStatements)
            ]
    where
        (extensionStatements, regularStatements) = partition isCreateExtension statements

-- | Returns whether a schema statement creates a PostgreSQL extension.
isCreateExtension :: Statement -> Bool
isCreateExtension CreateExtension {} = True
isCreateExtension _ = False

-- | Builds the conventional filename for a migration revision and slug.
migrationFileName :: Int -> Text -> Text
migrationFileName revision slug =
    tshow revision <> (if isEmpty slug then "" else "-" <> slug) <> ".sql"

diffAppDatabase includeIHPSchema databaseUrl = do
    (Right schemaSql) <- SchemaDesignerParser.parseSchemaSql
    (Right ihpSchemaSql) <- if includeIHPSchema
            then parseIHPSchema
            else pure (Right [])
    actualSchema <- getAppDBSchema databaseUrl

    let targetSchema = ihpSchemaSql <> schemaSql

    pure (diffSchemas targetSchema actualSchema)

parseIHPSchema :: IO (Either ByteString [Statement])
parseIHPSchema = do
    ihpSchemaSql <- findIHPSchemaSql
    Parser.parseSqlFile ihpSchemaSql

findIHPSchemaSql :: IO OsPath
findIHPSchemaSql = do
    fp <- getDataFileName ("IHPSchema.sql" :: String)
    let fpText :: Text = cs fp
    pure (textToOsPath fpText)

diffSchemas :: [Statement] -> [Statement] -> [Statement]
diffSchemas targetSchema' actualSchema' = (drop <> create)
            |> patchTable
            |> patchEnumType
            |> applyRenameTable
            |> removeImplicitDeletions actualSchema
            |> disableTransactionWhileAddingEnumValues
            |> applyReplaceFunction
    where
        create :: [Statement]
        create = targetSchema \\ actualSchema

        drop :: [Statement]
        drop = (actualSchema \\ targetSchema)
                |> mapMaybe toDropStatement

        targetSchema = removeNoise $ normalizeSchema targetSchema'
        actualSchema = removeNoise $ normalizeSchema actualSchema'

        -- | Replaces 'DROP TABLE x; CREATE TABLE x;' DDL sequences with a more efficient 'ALTER TABLE' sequence
        patchTable :: [Statement] -> [Statement]
        patchTable ((s@DropTable { tableName }):statements) =
                case createTable of
                    Just createTable -> (migrateTable createTable actualTable) <> patchTable (delete createTable statements)
                    Nothing -> s:(patchTable statements)
            where
                createTable :: Maybe Statement
                createTable = find isCreateTableStatement statements

                isCreateTableStatement :: Statement -> Bool
                isCreateTableStatement (StatementCreateTable { unsafeGetCreateTable = table }) | table.name == tableName = True
                isCreateTableStatement otherwise = False

                (Just actualTable) = actualSchema |> find \case
                        StatementCreateTable { unsafeGetCreateTable = table } -> table.name == tableName
                        otherwise                                                            -> False
        patchTable (s:rest) = s:(patchTable rest)
        patchTable [] = []

        -- | Replaces 'DROP TYPE x; CREATE TYPE x;' DDL sequences with a more efficient 'ALTER TYPE' sequence
        patchEnumType :: [Statement] -> [Statement]
        patchEnumType ((s@DropEnumType { name }):statements) =
                case createEnumType of
                    Just createEnumType -> (migrateEnum createEnumType actualEnumType) <> patchEnumType (delete createEnumType statements)
                    Nothing -> s:(patchEnumType statements)
            where
                createEnumType :: Maybe Statement
                createEnumType = find isCreateEnumTypeStatement statements

                isCreateEnumTypeStatement :: Statement -> Bool
                isCreateEnumTypeStatement CreateEnumType { name = n } = name == n
                isCreateEnumTypeStatement otherwise                   = False

                (Just actualEnumType) = actualSchema |> find \case
                        CreateEnumType { name = enum } -> enum == name
                        otherwise                      -> False
        patchEnumType (s:rest) = s:(patchEnumType rest)
        patchEnumType [] = []

        -- | Replaces 'DROP TABLE a; CREATE TABLE b;' DDL sequences with a more efficient 'ALTER TABLE a RENAME TO b' sequence if
        -- the tables have no differences except the name.
        applyRenameTable :: [Statement] -> [Statement]
        applyRenameTable ((s@DropTable { tableName }):statements) =
                case createTable of
                    Just createTable@(StatementCreateTable { unsafeGetCreateTable = createTable' }) ->
                        let
                            from = tableName
                            to = createTable'.name
                        in
                            (RenameTable { from, to }):(applyRenameTable (fixIdentifiers from to (delete createTable statements)))
                    Just _ -> s:(applyRenameTable statements)  -- Not a StatementCreateTable, skip rename
                    Nothing -> s:(applyRenameTable statements)
            where
                createTable :: Maybe Statement
                createTable = find isCreateTableStatement statements

                isCreateTableStatement :: Statement -> Bool
                isCreateTableStatement (StatementCreateTable { unsafeGetCreateTable = table }) = (table.name /= actualTable'.name) && ((actualTable' :: CreateTable) { name = "" } == (table :: CreateTable) { name = "" })
                isCreateTableStatement otherwise = False

                (Just actualTable) = actualSchema |> find \case
                        StatementCreateTable { unsafeGetCreateTable = table } -> table.name == tableName
                        otherwise                                                            -> False

                actualTable' :: CreateTable
                actualTable' = case actualTable of
                    StatementCreateTable { unsafeGetCreateTable = table } -> table
                    _ -> error "diffSchemas: expected StatementCreateTable"

                fixIdentifiers :: Text -> Text -> [Statement] -> [Statement]
                fixIdentifiers tableFrom tableTo statements = map fixIdentifier statements
                    where
                        fixIdentifier :: Statement -> Statement
                        fixIdentifier s@(DropConstraint { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier s@(DropPolicy { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier s@(DropTrigger { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier s@(EnableRowLevelSecurity { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier s@(ForceRowLevelSecurity { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier s@(NoForceRowLevelSecurity { tableName }) | tableName == tableFrom = s { tableName = tableTo }
                        fixIdentifier o = o
        applyRenameTable (s:rest) = s:(applyRenameTable rest)
        applyRenameTable [] = []

        toDropStatement :: Statement -> Maybe Statement
        toDropStatement StatementCreateTable { unsafeGetCreateTable = table } = Just DropTable { tableName = table.name }
        toDropStatement CreateEnumType { name } = Just DropEnumType { name }
        toDropStatement CreateIndex { indexName } = Just DropIndex { indexName }
        toDropStatement AddConstraint { tableName, constraint } = case constraint.name of
                Just constraintName -> Just DropConstraint { tableName, constraintName }
                Nothing -> Nothing
        toDropStatement CreatePolicy { tableName, name } = Just DropPolicy { tableName, policyName = name }
        toDropStatement CreateFunction { functionName } = Just DropFunction { functionName }
        toDropStatement CreateTrigger { name, tableName } = Just DropTrigger { name, tableName }
        toDropStatement CreateConstraintTrigger { name, tableName } = Just DropTrigger { name, tableName }
        toDropStatement CreateEventTrigger { name } = Just DropEventTrigger { name }
        toDropStatement ForceRowLevelSecurity { tableName } = Just NoForceRowLevelSecurity { tableName }
        toDropStatement otherwise = Nothing


        -- | Replaces 'DROP FUNCTION a; CREATE FUNCTION a ..;' DDL sequences with a more efficient 'CREATE OR REPLACE FUNCTION a' sequence if
        -- the function have no differences except the body.
        applyReplaceFunction :: [Statement] -> [Statement]
        applyReplaceFunction (DropFunction { functionName }:statements) =
            statements
                |> map \case
                    s@(CreateFunction { functionName = newFunctionName }) | newFunctionName == functionName -> (s { orReplace = True })
                    otherwise -> otherwise
                |> applyReplaceFunction
        applyReplaceFunction (s:rest) = s:(applyReplaceFunction rest)
        applyReplaceFunction [] = []

removeNoise = filter \case
        Comment {} -> False
        -- IHP cannot compare unmodelled SQL safely. Never copy it from either
        -- side into an automatically generated migration.
        UnknownStatement {} -> False
        -- pg_dump session setup is not part of the application schema.
        Set {} -> False
        SelectStatement {} -> False
        StatementCreateTable { unsafeGetCreateTable = CreateTable { name = "schema_migrations" } }      -> False
        AddConstraint { tableName = "schema_migrations" }                                               -> False
        CreateFunction { functionName } | "notify_" `Text.isPrefixOf` functionName                      -> False
        CreateTrigger { name } | any (`Text.isPrefixOf` name) ["did_update_", "did_delete_", "did_insert_", "ar_did_update_", "ar_did_delete_", "ar_did_insert_"] -> False
        StatementCreateTable { unsafeGetCreateTable = CreateTable { name = "large_pg_notifications" } } -> False
        CreateIndex { tableName = "large_pg_notifications" }                                            -> False
        _                                                                                               -> True

migrateTable :: Statement -> Statement -> [Statement]
migrateTable StatementCreateTable { unsafeGetCreateTable = targetTable } StatementCreateTable { unsafeGetCreateTable = actualTable } = migrateTable' targetTable actualTable
    where
        migrateTable' CreateTable { name = tableName, columns = targetColumns } CreateTable { columns = actualColumns } =
                (map dropColumn dropColumns <> map createColumn createColumns)
                    |> applyRenameColumn
                    |> applyMakeUnique
                    |> applySetDefault
                    |> applyToggleNull
            where

                createColumns :: [Column]
                createColumns = targetColumns \\ actualColumns

                dropColumns :: [Column]
                dropColumns = actualColumns \\ targetColumns

                createColumn :: Column -> Statement
                createColumn column = AddColumn { tableName, column }

                dropColumn :: Column -> Statement
                dropColumn column = DropColumn { tableName, columnName = column.name }

                applyRenameColumn (s@(DropColumn { columnName }):statements) = case matchingCreateColumn of
                        Just matchingCreateColumn -> RenameColumn { tableName, from = columnName, to = matchingCreateColumn.column.name } : (applyRenameColumn (filter ((/=) matchingCreateColumn) statements))
                        Nothing -> s:(applyRenameColumn statements)
                    where
                        matchingCreateColumn :: Maybe Statement
                        matchingCreateColumn = find isMatchingCreateColumn statements

                        isMatchingCreateColumn :: Statement -> Bool
                        isMatchingCreateColumn AddColumn { column = addColumn } = actualColumns
                                |> find \case
                                    Column { name } -> name == columnName
                                |> maybe False (\c -> (c :: Column) { name = addColumn.name } == addColumn)
                        isMatchingCreateColumn otherwise                          = False
                applyRenameColumn (statement:rest) = statement:(applyRenameColumn rest)
                applyRenameColumn [] = []

                -- | Emits 'ALTER TABLE table ADD UNIQUE (column);'
                --
                -- This function substitutes the following queries:
                --
                -- > ALTER TABLE table DROP COLUMN column;
                -- > ALTER TABLE table ADD COLUMN column UNIQUE;
                --
                -- With a more natural @ADD UNIQUE@:
                --
                -- > ALTER TABLE table ADD UNIQUE (column);
                --
                applyMakeUnique (s@(DropColumn { columnName }):statements) = case matchingCreateColumn of
                        Just matchingCreateColumn -> updateConstraint:(applyMakeUnique (filter ((/=) matchingCreateColumn) statements))
                        Nothing -> s:(applyMakeUnique statements)
                    where
                        dropColumn :: Column
                        (Just dropColumn) = actualColumns
                                |> find \case
                                    Column { name } -> name == columnName

                        updateConstraint = if dropColumn.isUnique
                            then DropConstraint { tableName, constraintName = tableName <> "_" <> (dropColumn.name) <> "_key" }
                            else AddConstraint { tableName, constraint = UniqueConstraint { name = Nothing, columnNames = [dropColumn.name] }, deferrable = Nothing, deferrableType = Nothing }

                        matchingCreateColumn :: Maybe Statement
                        matchingCreateColumn = find isMatchingCreateColumn statements

                        isMatchingCreateColumn :: Statement -> Bool
                        isMatchingCreateColumn AddColumn { column = addColumn } = addColumn { isUnique = False } == dropColumn { isUnique = False }
                        isMatchingCreateColumn otherwise                        = False
                applyMakeUnique (statement:rest) = statement:(applyMakeUnique rest)
                applyMakeUnique [] = []

                -- | Emits "ALTER TABLE table ALTER COLUMN column SET DEFAULT 'value'"
                --
                -- This function substitutes the following queries:
                --
                -- > ALTER TABLE table DROP COLUMN column;
                -- > ALTER TABLE table ADD COLUMN column;
                --
                -- With a more natural @SET DEFAULT@:
                --
                -- > ALTER TABLE table ALTER COLUMN column SET DEFAULT 'value'
                --
                applySetDefault (s@(DropColumn { columnName }):statements) = case matchingCreateColumn of
                        Just matchingCreateColumn -> case matchingCreateColumn.column.defaultValue of
                            Just value -> SetDefaultValue { tableName, columnName, value }:rest
                            Nothing -> DropDefaultValue { tableName, columnName }:rest
                            where
                                rest = applySetDefault (filter ((/=) matchingCreateColumn) statements)
                        Nothing -> s:(applySetDefault statements)
                    where
                        dropColumn :: Column
                        (Just dropColumn) = actualColumns
                                |> find \case
                                    Column { name } -> name == columnName

                        matchingCreateColumn :: Maybe Statement
                        matchingCreateColumn = find isMatchingCreateColumn statements

                        isMatchingCreateColumn :: Statement -> Bool
                        isMatchingCreateColumn AddColumn { column = addColumn } = (addColumn { defaultValue = Nothing } :: Column) == (dropColumn { defaultValue = Nothing } :: Column)
                        isMatchingCreateColumn otherwise                        = False
                applySetDefault (statement:rest) = statement:(applySetDefault rest)
                applySetDefault [] = []

                -- | Emits 'ALTER TABLE table ALTER COLUMN column DROP NOT NULL'
                --
                -- This function substitutes the following queries:
                --
                -- > ALTER TABLE table DROP COLUMN column;
                -- > ALTER TABLE table ADD COLUMN column;
                --
                -- With a more natural @DROP NOT NULL@:
                --
                -- > ALTER TABLE table ALTER COLUMN column DROP NOT NULL
                --
                applyToggleNull (s@(DropColumn { columnName }):statements) = case matchingCreateColumn of
                        Just matchingCreateColumn -> updateConstraint:(applyToggleNull (filter ((/=) matchingCreateColumn) statements))
                        Nothing -> s:(applyToggleNull statements)
                    where
                        dropColumn :: Column
                        (Just dropColumn) = actualColumns
                                |> find \case
                                    Column { name } -> name == columnName

                        updateConstraint = if dropColumn.notNull
                            then DropNotNull { tableName, columnName = dropColumn.name }
                            else SetNotNull { tableName, columnName = dropColumn.name }

                        matchingCreateColumn :: Maybe Statement
                        matchingCreateColumn = find isMatchingCreateColumn statements

                        isMatchingCreateColumn :: Statement -> Bool
                        isMatchingCreateColumn AddColumn { column = addColumn } = addColumn `eqColumnExceptNull` dropColumn
                        isMatchingCreateColumn otherwise                        = False

                        eqColumnExceptNull :: Column -> Column -> Bool
                        eqColumnExceptNull colA colB = (normalizeCol colA) == (normalizeCol colB)
                            where
                                normalizeCol col = col { notNull = False, defaultValue = Just (VarExpression "null") }
                applyToggleNull (statement:rest) = statement:(applyToggleNull rest)
                applyToggleNull [] = []
migrateTable _ _ = error "migrateTable: expected StatementCreateTable"

migrateEnum :: Statement -> Statement -> [Statement]
migrateEnum CreateEnumType { name, values = targetValues } CreateEnumType { values = actualValues } = map addValue newValues
    where
        newValues :: [Text]
        newValues = targetValues \\ actualValues

        addValue :: Text -> Statement
        addValue value = AddValueToEnumType { enumName = name, newValue = value, ifNotExists = True }
migrateEnum _ _ = error "migrateEnum: expected CreateEnumType"

getAppDBSchema :: Text -> IO [Statement]
getAppDBSchema databaseUrl = do
    sql <- dumpAppDatabaseSchema databaseUrl
    case parseDumpedSql sql of
        Left error -> fail (cs error)
        Right result -> pure result

-- | Returns the DDL statements of the locally running dev db
--
-- Basically does the same as @make dumpdb@ but returns the output as a string
dumpAppDatabaseSchema :: Text -> IO Text
dumpAppDatabaseSchema databaseUrl = do
    projectDir <- Directory.getCurrentDirectory
    cs <$> Process.readProcess "pg_dump" ["-s", "--no-owner", "--no-acl", cs databaseUrl] []

parseDumpedSql :: Text -> (Either ByteString [Statement])
parseDumpedSql sql =
    case runParser Parser.parseDDL "pg_dump" sql of
        Left error -> Left (cs $ errorBundlePretty error)
        Right r -> Right r

normalizeSchema :: [Statement] -> [Statement]
normalizeSchema statements = map normalizeStatement statements
        |> concat
        |> normalizeForeignKeyNameCollisions
        |> normalizePrimaryKeys
        |> normalizeCompositeForeignKeyReferences

normalizeForeignKeyNameCollisions :: [Statement] -> [Statement]
normalizeForeignKeyNameCollisions = go []
    where
        go _ [] = []
        go usedNames (statement@AddConstraint { tableName, constraint } : rest)
            | isForeignKey constraint =
                case constraint.name of
                    Just explicitName -> statement : go ((tableName, explicitName) : usedNames) rest
                    Nothing ->
                        let baseName = generatedForeignKeyName tableName constraint
                            uniqueName = firstAvailableName tableName baseName usedNames
                            normalizedConstraint = setForeignKeyName uniqueName constraint
                        in statement { constraint = normalizedConstraint } : go ((tableName, uniqueName) : usedNames) rest
            | Just explicitName <- constraint.name =
                statement : go ((tableName, explicitName) : usedNames) rest
        go usedNames (statement@(StatementCreateTable CreateTable { name, constraints }) : rest) =
            statement : go (map (\constraintName -> (name, constraintName)) (mapMaybe (.name) constraints) <> usedNames) rest
        go usedNames (statement : rest) = statement : go usedNames rest

        generatedForeignKeyName tableName ForeignKeyConstraint { columnName } =
            postgresGeneratedObjectName (unqualifiedRelationName tableName) columnName "fkey"
        generatedForeignKeyName tableName CompositeForeignKeyConstraint { columnNames } =
            postgresGeneratedObjectName (unqualifiedRelationName tableName) (Text.intercalate "_" columnNames) "fkey"
        generatedForeignKeyName _ _ = error "generatedForeignKeyName: expected a foreign key"

        unqualifiedRelationName tableName = fromMaybe tableName (last (Text.splitOn "." tableName))

        isForeignKey ForeignKeyConstraint {} = True
        isForeignKey CompositeForeignKeyConstraint {} = True
        isForeignKey _ = False

        setForeignKeyName uniqueName (ForeignKeyConstraint _ columnName referenceTable referenceColumn onDelete onUpdate constraintDeferrable constraintDeferrableType) =
            ForeignKeyConstraint (Just uniqueName) columnName referenceTable referenceColumn onDelete onUpdate constraintDeferrable constraintDeferrableType
        setForeignKeyName uniqueName (CompositeForeignKeyConstraint _ columnNames referenceTable referenceColumns matchType onDelete onUpdate constraintDeferrable constraintDeferrableType) =
            CompositeForeignKeyConstraint (Just uniqueName) columnNames referenceTable referenceColumns matchType onDelete onUpdate constraintDeferrable constraintDeferrableType
        setForeignKeyName _ constraint = constraint

        firstAvailableName tableName baseName usedNames = findAvailable 0
            where
                findAvailable index
                    | (tableName, candidate index) `elem` usedNames = findAvailable (index + 1)
                    | otherwise = candidate index
                candidate 0 = baseName
                candidate index =
                    let suffix = tshow index
                    in truncateUtf8ToBytes (63 - utf8Length suffix) baseName <> suffix

normalizeCompositeForeignKeyReferences :: [Statement] -> [Statement]
normalizeCompositeForeignKeyReferences statements = map resolveReferenceColumns statements
    where
        resolveReferenceColumns statement@(AddConstraint { constraint = constraint@CompositeForeignKeyConstraint { referenceTable, referenceColumns = [] } }) =
            statement { constraint = constraint { referenceColumns = referencedPrimaryKey referenceTable } }
        resolveReferenceColumns statement = statement

        referencedPrimaryKey referenceTable = fromMaybe [] do
            StatementCreateTable { unsafeGetCreateTable = CreateTable { primaryKeyConstraint = PrimaryKeyConstraint { primaryKeyColumnNames } } } <- find isReferencedTable statements
            pure (map Text.toLower primaryKeyColumnNames)
            where
                isReferencedTable StatementCreateTable { unsafeGetCreateTable = CreateTable { name } } = name == referenceTable
                isReferencedTable _ = False

normalizeStatement :: Statement -> [Statement]
normalizeStatement StatementCreateTable { unsafeGetCreateTable = table } = StatementCreateTable { unsafeGetCreateTable = normalizedTable } : normalizeTableRest
    where
        (normalizedTable, normalizeTableRest) = normalizeTable table
normalizeStatement AddConstraint { tableName, constraint, deferrable, deferrableType } = [ AddConstraint { tableName, constraint = normalizeConstraint tableName constraint, deferrable, deferrableType } ]
normalizeStatement CreateEnumType { name, values } = [ CreateEnumType { name = Text.toLower name, values = map Text.toLower values } ]
normalizeStatement CreatePolicy { name, action, tableName, roles, using, check } = [ CreatePolicy { name = truncateIdentifier name, tableName, roles = normalizePolicyRoles roles, using = (unqualifyExpression tableName . normalizeExpression) <$> using, check = (unqualifyExpression tableName . normalizeExpression) <$> check, action = normalizePolicyAction action } ]
normalizeStatement CreateIndex { columns, indexType, indexName, .. } = [ CreateIndex { columns = map normalizeIndexColumn columns, indexType = normalizeIndexType indexType, indexName = truncateIdentifier indexName, .. } ]
normalizeStatement CreateFunction { functionArguments, returns, .. } = [ CreateFunction { orReplace = False, language = Text.toUpper language, functionArguments = map (\(name, type_) -> (name, normalizeSqlType type_)) functionArguments, returns = normalizeSqlType returns, functionAttributes = normalizedFunctionAttributes, functionBody = removeIndentation $ normalizeNewLines functionBody, .. } ]
    where
        normalizedFunctionAttributes = sortOn functionAttributeOrder (filter (not . isDefaultFunctionAttribute) (map normalizeFunctionAttribute functionAttributes))
        isDefaultFunctionAttribute attribute =
            attribute `elem` ["VOLATILE", "NOT LEAKPROOF", "CALLED ON NULL INPUT", "SECURITY INVOKER", "PARALLEL UNSAFE"]
                || (Text.toUpper language `elem` ["SQL", "PLPGSQL"] && numericAttributeEquals "COST " 100 attribute)
                || (isSetReturning && numericAttributeEquals "ROWS " 1000 attribute)
        isSetReturning = case returns of
            PSetOf {} -> True
            PTable {} -> True
            _ -> False
        numericAttributeEquals prefix expected attribute = case Text.stripPrefix prefix attribute of
            Just value -> Read.readMaybe (cs value) == Just (expected :: Double)
            Nothing -> False
        normalizeFunctionAttribute attribute
            | Just supportFunction <- Text.stripPrefix "SUPPORT " attribute = "SUPPORT " <> normalizeCustomType supportFunction
            | Just typeName <- Text.stripPrefix "TRANSFORM FOR TYPE " attribute = "TRANSFORM FOR TYPE " <> normalizeCustomType typeName
            | Just value <- Text.stripPrefix "COST " normalizedAttribute = "COST " <> normalizeNumericLiteral value
            | Just value <- Text.stripPrefix "ROWS " normalizedAttribute = "ROWS " <> normalizeNumericLiteral value
            | otherwise = case normalizedAttribute of
                "RETURNS NULL ON NULL INPUT" -> "STRICT"
                normalized -> normalized
            where
                normalizedAttribute = Text.toUpper attribute
        functionAttributeOrder attribute
            | attribute `elem` ["IMMUTABLE", "STABLE", "VOLATILE"] = (0 :: Int)
            | "LEAKPROOF" `Text.isInfixOf` attribute = 1
            | attribute == "WINDOW" = 2
            | attribute `elem` ["STRICT", "CALLED ON NULL INPUT", "RETURNS NULL ON NULL INPUT"] = 3
            | "SECURITY " `Text.isPrefixOf` attribute = 4
            | "PARALLEL " `Text.isPrefixOf` attribute = 5
            | "COST " `Text.isPrefixOf` attribute = 6
            | "ROWS " `Text.isPrefixOf` attribute = 7
            | "SUPPORT " `Text.isPrefixOf` attribute = 8
            | "TRANSFORM FOR TYPE " `Text.isPrefixOf` attribute = 9
            | otherwise = 10
normalizeStatement trigger@CreateTrigger { event, whenCondition } = [trigger { event = map normalizeTriggerEvent event, whenCondition = normalizeTriggerExpression <$> whenCondition }]
normalizeStatement trigger@CreateConstraintTrigger { name, event, tableName, referencedTableName, deferrable, deferrableType, whenCondition, functionName } =
    [ trigger
        { name
        , event = map normalizeTriggerEvent event
        , tableName
        , referencedTableName
        , whenCondition = normalizeTriggerExpression <$> whenCondition
        , deferrable = if deferrable == Just False then Nothing else deferrable
        , deferrableType = if deferrableType == Just InitiallyImmediate then Nothing else deferrableType
        , functionName = Text.toLower functionName
        }
    ]
normalizeStatement statement@CreateSequence { sequenceOptions } = [statement { sequenceOptions = normalizeSequenceOptions sequenceOptions }]
normalizeStatement statement@CreateExtension { extensionOptions } = [statement { extensionOptions = filter (not . isImplicitExtensionOption) extensionOptions }]
normalizeStatement NoForceRowLevelSecurity {} = []
normalizeStatement otherwise = [otherwise]

normalizeTriggerEvent :: TriggerEvent -> TriggerEvent
normalizeTriggerEvent (TriggerOnUpdateOf columns) = TriggerOnUpdateOf columns
normalizeTriggerEvent event = event

normalizeSequenceOptions :: [SequenceOption] -> [SequenceOption]
normalizeSequenceOptions options = sortOn sequenceOptionKind (filter (not . isImplicitSequenceOption implicitStart defaultMinValue defaultMaxValue) options)
    where
        sequenceType = fromMaybe PBigInt (listToMaybe [postgresType | SequenceAs postgresType <- options])
        typeMinValue = IntExpression case sequenceType of
            PSmallInt -> -32768
            PInt -> -2147483648
            _ -> -9223372036854775808
        typeMaxValue = IntExpression case sequenceType of
            PSmallInt -> 32767
            PInt -> 2147483647
            _ -> 9223372036854775807
        defaultMinValue = if any isDescendingIncrement options then typeMinValue else IntExpression 1
        defaultMaxValue = if any isDescendingIncrement options then IntExpression (-1) else typeMaxValue
        implicitStart
            | any isDescendingIncrement options = fromMaybe (IntExpression (-1)) (listToMaybe [value | SequenceMaxValue value <- options])
            | otherwise = fromMaybe (IntExpression 1) (listToMaybe [value | SequenceMinValue value <- options])
        isDescendingIncrement (SequenceIncrement (IntExpression value)) = value < 0
        isDescendingIncrement _ = False

sequenceOptionKind :: SequenceOption -> Int
sequenceOptionKind = \case
    SequenceAs {} -> 0
    SequenceStart {} -> 1
    SequenceIncrement {} -> 2
    SequenceNoMinValue -> 3
    SequenceMinValue {} -> 3
    SequenceNoMaxValue -> 4
    SequenceMaxValue {} -> 4
    SequenceCache {} -> 5
    SequenceCycle {} -> 6

isImplicitSequenceOption :: Expression -> Expression -> Expression -> SequenceOption -> Bool
isImplicitSequenceOption implicitStart _ _ (SequenceStart value) = value == implicitStart
isImplicitSequenceOption _ _ _ (SequenceAs PBigInt) = True
isImplicitSequenceOption _ _ _ (SequenceIncrement (IntExpression 1)) = True
isImplicitSequenceOption _ _ _ SequenceNoMinValue = True
isImplicitSequenceOption _ _ _ SequenceNoMaxValue = True
isImplicitSequenceOption _ defaultMinValue _ (SequenceMinValue value) = value == defaultMinValue
isImplicitSequenceOption _ _ defaultMaxValue (SequenceMaxValue value) = value == defaultMaxValue
isImplicitSequenceOption _ _ _ (SequenceCache (IntExpression 1)) = True
isImplicitSequenceOption _ _ _ (SequenceCycle False) = True
isImplicitSequenceOption _ _ _ _ = False

isImplicitExtensionOption :: ExtensionOption -> Bool
isImplicitExtensionOption ExtensionSchema {} = True
isImplicitExtensionOption ExtensionVersion {} = True
isImplicitExtensionOption ExtensionCascade = True

normalizePolicyAction (Just PolicyForAll) = Nothing
normalizePolicyAction otherwise = otherwise

normalizePolicyRoles :: [PolicyRole] -> [PolicyRole]
normalizePolicyRoles roles
    | any isPublicRole roles = []
    | otherwise = map normalizeLiteralRole roles
    where
        isPublicRole (SpecialPolicyRole role) = foldAsciiUpper role == "PUBLIC"
        isPublicRole _ = False
        normalizeLiteralRole (PolicyRole role) = PolicyRole (truncateIdentifier role)
        normalizeLiteralRole (QuotedPolicyRole role) = QuotedPolicyRole (truncateIdentifier role)
        normalizeLiteralRole role = role

foldAsciiUpper :: Text -> Text
foldAsciiUpper = Text.map \character ->
    if character >= 'a' && character <= 'z' then Char.toUpper character else character

normalizeTable :: CreateTable -> (CreateTable, [Statement])
normalizeTable table@(CreateTable { .. }) = ( CreateTable { columns = fst normalizedColumns, constraints = normalizedTableConstraints, .. }, (concat $ (snd normalizedColumns)) <> normalizedConstraintsStatements )
    where
        normalizedColumns = columns
                |> map (normalizeColumn table)
                |> unzip

        -- pg_dump typically inlines the table constraints into the CREATE TABLE statement like this:
        --
        -- > CREATE TABLE public.a (
        -- >     id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
        -- >     CONSTRAINT c CHECK 1=1
        -- > );
        --
        -- In IHP we typically split this into a 'CREATE TABLE' statement and into a 'ALTER TABLE .. ADD CONSTRAINT ..' statement.
        --
        -- We normalize the above statement to this:
        --
        -- > CREATE TABLE public.a (
        -- >     id uuid DEFAULT public.uuid_generate_v4() NOT NULL
        -- > );
        -- > ALTER TABLE a ADD CONSTRAINT c CHECK 1=1;
        normalizedDetachedConstraints :: [Either Statement Constraint]
        normalizedDetachedConstraints = constraints
                |> map \case
                    constraint@(CheckConstraint {}) -> detach constraint
                    constraint@(ForeignKeyConstraint {}) -> detachForeignKey constraint
                    constraint@(CompositeForeignKeyConstraint {}) -> detachForeignKey constraint
                    otherConstraint -> Right otherConstraint
            where
                detach constraint = Left AddConstraint { tableName = name, constraint = normalizeConstraint name constraint, deferrable = Nothing, deferrableType = Nothing }
                detachForeignKey constraint = Left AddConstraint
                    { tableName = name
                    , constraint = normalizeConstraint name constraint { constraintDeferrable = Nothing, constraintDeferrableType = Nothing }
                    , deferrable = constraint.constraintDeferrable
                    , deferrableType = constraint.constraintDeferrableType
                    }

        normalizedTableConstraints :: [Constraint]
        normalizedTableConstraints =
            normalizedDetachedConstraints
            |> mapMaybe \case
                Left _ -> Nothing
                Right c -> Just c

        normalizedConstraintsStatements :: [Statement]
        normalizedConstraintsStatements =
            normalizedDetachedConstraints
            |> mapMaybe \case
                Right _ -> Nothing
                Left c -> Just c

normalizeConstraint :: Text -> Constraint -> Constraint
normalizeConstraint tableName ForeignKeyConstraint { name, columnName, referenceTable, referenceColumn, onDelete, onUpdate, constraintDeferrable, constraintDeferrableType } = ForeignKeyConstraint { name = normalizeForeignKeyName tableName [columnName] name, columnName, referenceTable, referenceColumn, onDelete = normalizeReferentialAction onDelete, onUpdate = normalizeReferentialAction onUpdate, constraintDeferrable, constraintDeferrableType }
normalizeConstraint tableName CompositeForeignKeyConstraint { name, columnNames, referenceTable, referenceColumns, matchType, onDelete, onUpdate, constraintDeferrable, constraintDeferrableType } = CompositeForeignKeyConstraint
    { name = normalizeForeignKeyName tableName columnNames name
    , columnNames
    , referenceTable
    , referenceColumns
    , matchType = normalizeMatchType matchType
    , onDelete = normalizeReferentialAction onDelete
    , onUpdate = normalizeReferentialAction onUpdate
    , constraintDeferrable
    , constraintDeferrableType
    }

normalizeConstraint tableName constraint@(UniqueConstraint { name = Just uniqueName, columnNames }) | length columnNames > 1 =
        -- Single column UNIQUE constraints like:
        --
        -- > ALTER TABLE ONLY public.users ADD CONSTRAINT users_github_user_id_key UNIQUE (github_user_id);
        --
        -- are packed into the CREATE TABLE definition:
        --
        -- > CREATE TABLE users (
        -- >     id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
        -- >     github_user_id INT DEFAULT NULL UNIQUE
        -- > );
        --
        -- For multi columns we need to normalize the name, e.g.:
        --
        -- > ALTER TABLE days ADD UNIQUE (category_id, date);
        --
        -- Is the same as:
        --
        -- > ALTER TABLE ONLY public.days ADD CONSTRAINT days_category_id_date_key UNIQUE (category_id, date);
        --
        let
            defaultName = ([tableName] <> columnNames <> ["key"])
                    |> Text.intercalate "_" 
        in
            if uniqueName == defaultName
                then constraint { name = Nothing }
                else constraint
normalizeConstraint _ otherwise = otherwise

normalizeForeignKeyName :: Text -> [Text] -> Maybe Text -> Maybe Text
normalizeForeignKeyName _ _ name = truncateUtf8ToBytes 63 <$> name

-- PostgreSQL's makeObjectName balances truncation between the relation and
-- column components, clips on a UTF-8 boundary, and always keeps the suffix.
postgresGeneratedObjectName :: Text -> Text -> Text -> Text
postgresGeneratedObjectName firstName secondName suffix =
    truncateUtf8ToBytes firstBytes firstName
        <> "_" <> truncateUtf8ToBytes secondBytes secondName
        <> "_" <> suffix
    where
        availableBytes = 63 - utf8Length suffix - 2
        (firstBytes, secondBytes) = balance (utf8Length firstName) (utf8Length secondName)

        balance firstLength secondLength
            | firstLength + secondLength <= availableBytes = (firstLength, secondLength)
            | firstLength > secondLength = balance (firstLength - 1) secondLength
            | otherwise = balance firstLength (secondLength - 1)

truncateUtf8ToBytes :: Int -> Text -> Text
truncateUtf8ToBytes byteLimit = Text.pack . go byteLimit . Text.unpack
    where
        go _ [] = []
        go remaining (character : rest)
            | characterBytes <= remaining = character : go (remaining - characterBytes) rest
            | otherwise = []
            where
                characterBytes = utf8Length (Text.singleton character)

utf8Length :: Text -> Int
utf8Length = ByteString.length . TextEncoding.encodeUtf8

normalizeMatchType :: Maybe ForeignKeyMatchType -> Maybe ForeignKeyMatchType
normalizeMatchType (Just MatchSimple) = Nothing
normalizeMatchType matchType = matchType

normalizeReferentialAction action = Just case fromMaybe NoAction action of
    SetNull columnNames -> SetNull columnNames
    SetDefault columnNames -> SetDefault columnNames
    other -> other

normalizeColumn :: CreateTable -> Column -> (Column, [Statement])
normalizeColumn table Column { name, columnType, defaultValue, notNull, notNullConstraintName, isUnique, generator } = (Column { name, columnType = normalizeSqlType columnType, defaultValue = normalizedDefaultValue, notNull, notNullConstraintName, isUnique = False, generator = normalizeColumnGenerator <$> generator }, uniqueConstraint)
    where
        uniqueConstraint =
            if isUnique
                then [ AddConstraint { tableName = table.name, constraint = UniqueConstraint (Just $ (table.name) <>"_" <> name <> "_key") [name], deferrable = Nothing, deferrableType = Nothing } ]
                else []

        normalizedDefaultValue = case defaultValue of
            Just defaultValue -> Just (normalizeDefaultExpression columnType defaultValue)
            Nothing -> if notNull || isJust generator
                then Nothing
                else Just (VarExpression "null") -- pg_dump columns don't have an explicit default null value

normalizeColumnGenerator :: ColumnGenerator -> ColumnGenerator
normalizeColumnGenerator generator@(ColumnGenerator { generate }) = generator { generate = normalizeExpression generate }

normalizeExpression :: Expression -> Expression
normalizeExpression = normalizeExpressionWith False

normalizeTriggerExpression :: Expression -> Expression
normalizeTriggerExpression = normalizeExpressionWith True

normalizeExpressionWith :: Bool -> Expression -> Expression
normalizeExpressionWith preserveSemanticCasts = normalize
    where
        normalize e@(TextExpression {}) = e
        normalize (VarExpression var) = VarExpression (Text.toLower var)
        normalize (CallExpression function args) = CallExpression (Text.toLower function) (map normalize args)
        normalize (NotEqExpression a b) = normalizeComparison NotEqExpression a b
        normalize (EqExpression a b) = normalizeComparison EqExpression a b
        normalize (AndExpression a b) = AndExpression (normalize a) (normalize b)
        normalize (IsExpression a b) = IsExpression (normalize a) (normalize b)
        normalize (InExpression a b) = InExpression (normalize a) (normalize b)
        normalize (NotExpression a) = NotExpression (normalize a)
        normalize (OrExpression a b) = OrExpression (normalize a) (normalize b)
        normalize (LessThanExpression a b) = normalizeComparison LessThanExpression a b
        normalize (LessThanOrEqualToExpression a b) = normalizeComparison LessThanOrEqualToExpression a b
        normalize (GreaterThanExpression a b) = normalizeComparison GreaterThanExpression a b
        normalize (GreaterThanOrEqualToExpression a b) = normalizeComparison GreaterThanOrEqualToExpression a b
        normalize e@(DoubleExpression {}) = e
        normalize e@(NumericExpression {}) = e
        normalize e@(IntExpression {}) = e
        normalize (ConcatenationExpression a b) = ConcatenationExpression (normalize a) (normalize b)
        normalize (BinaryOperatorExpression operator a b) = BinaryOperatorExpression operator (normalize a) (normalize b)
-- Enum default values from pg_dump always have an explicit type cast. Inside the Schema.sql they typically don't have those.
-- Therefore we remove these typecasts here
--
-- 'job_status_not_started'::public.job_status => 'job_status_not_started'
--
        normalize (TypeCastExpression expression postgresType)
            | preserveSemanticCasts = TypeCastExpression (normalize expression) (normalizeSqlType postgresType)
            | otherwise = normalize expression
        normalize (SelectExpression Select { columns, from, whereClause, alias }) = SelectExpression Select { columns = resolveAlias' <$> (normalize <$> columns), from = normalizeFrom from, whereClause = resolveAlias' (normalize whereClause), alias = Nothing }
            where
                -- Turns a `SELECT 1 FROM a` into `SELECT 1 FROM public.a`
                normalizeFrom (VarExpression a) = DotExpression (VarExpression "public") a
                normalizeFrom otherwise = normalize otherwise

                resolveAlias' = resolveAlias alias (unqualifiedName from)

                unqualifiedName :: Expression -> Expression
                unqualifiedName (DotExpression (VarExpression _) name) = VarExpression name
                unqualifiedName name = name
        normalize (DotExpression a b) = DotExpression (normalize a) (Text.toLower b)
        normalize (ExistsExpression a) = ExistsExpression (normalize a)
        normalize (InArrayExpression exprs) = InArrayExpression (map normalize exprs)
        normalize (ArrayLiteralExpression exprs) = ArrayLiteralExpression (map normalize exprs)
        normalize (VariadicExpression expr) = VariadicExpression (normalize expr)

        normalizeComparison constructor a b = constructor (normalizeComparisonOperand b a) (normalizeComparisonOperand a b)
        normalizeComparisonOperand other (TypeCastExpression expression PText)
            | preserveSemanticCasts && isLiteralExpression expression && not (isLiteralOperand other) = normalize expression
        normalizeComparisonOperand _ operand = normalize operand

        isLiteralExpression TextExpression {} = True
        isLiteralExpression DoubleExpression {} = True
        isLiteralExpression IntExpression {} = True
        isLiteralExpression _ = False
        isLiteralOperand (TypeCastExpression expression _) = isLiteralExpression expression
        isLiteralOperand expression = isLiteralExpression expression

normalizeDefaultExpression :: PostgresType -> Expression -> Expression
normalizeDefaultExpression columnType expression
    | supportsEquivalentNumericLiterals (normalizeSqlType columnType) = normalizeNumericExpression (normalizeExpression expression)
    | otherwise = normalizeExpression expression
    where
        supportsEquivalentNumericLiterals PReal = True
        supportsEquivalentNumericLiterals PDouble = True
        supportsEquivalentNumericLiterals PNumeric { scale = Just _ } = True
        supportsEquivalentNumericLiterals _ = False

        normalizeNumericExpression (DoubleExpression value) = NumericExpression (normalizeNumericLiteral (tshow value))
        normalizeNumericExpression (NumericExpression value) = NumericExpression (normalizeNumericLiteral value)
        normalizeNumericExpression (IntExpression value) = NumericExpression (normalizeNumericLiteral (tshow value))
        normalizeNumericExpression other = other

-- | Replaces @table.field@ with just @field@
--
-- >>> unqualifyExpression "servers" (sql "SELECT * FROM servers WHERE servers.is_public")
-- sql "SELECT * FROM servers WHERE is_public"
--
unqualifyExpression :: Text -> Expression -> Expression
unqualifyExpression scope expression = doUnqualify expression
    where
        doUnqualify e@(TextExpression {}) = e
        doUnqualify e@(VarExpression {}) = e
        doUnqualify (CallExpression function args) = CallExpression function (map doUnqualify args)
        doUnqualify (NotEqExpression a b) = NotEqExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (EqExpression a b) = EqExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (AndExpression a b) = AndExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (IsExpression a b) = IsExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (InExpression a b) = InExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (NotExpression a) = NotExpression (doUnqualify a)
        doUnqualify (OrExpression a b) = OrExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (LessThanExpression a b) = LessThanExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (LessThanOrEqualToExpression a b) = LessThanOrEqualToExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (GreaterThanExpression a b) = GreaterThanExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (GreaterThanOrEqualToExpression a b) = GreaterThanOrEqualToExpression (doUnqualify a) (doUnqualify b)
        doUnqualify e@(DoubleExpression {}) = e
        doUnqualify e@(NumericExpression {}) = e
        doUnqualify e@(IntExpression {}) = e
        doUnqualify (ConcatenationExpression a b) = ConcatenationExpression (doUnqualify a) (doUnqualify b)
        doUnqualify (TypeCastExpression a b) = TypeCastExpression (doUnqualify a) b
        doUnqualify e@(SelectExpression Select { columns, from, whereClause, alias }) =
            let recurse = case from of
                    VarExpression fromName -> doUnqualify . unqualifyExpression fromName
                    DotExpression (VarExpression "public") fromName -> doUnqualify . unqualifyExpression fromName
                    _ -> doUnqualify
            in
                SelectExpression Select { columns = (recurse <$> columns), from = from, whereClause = recurse whereClause, alias }
        doUnqualify (ExistsExpression a) = ExistsExpression (doUnqualify a)
        doUnqualify (InArrayExpression exprs) = InArrayExpression (map doUnqualify exprs)
        doUnqualify (ArrayLiteralExpression exprs) = ArrayLiteralExpression (map doUnqualify exprs)
        doUnqualify (VariadicExpression expr) = VariadicExpression (doUnqualify expr)
        doUnqualify (DotExpression (VarExpression scope') b) | scope == scope' = VarExpression b
        doUnqualify (DotExpression a b) = DotExpression (doUnqualify a) b


resolveAlias :: Maybe Text -> Expression -> Expression -> Expression
resolveAlias (Just alias) fromExpression expression =
    let
        rec = resolveAlias (Just alias) fromExpression
    in case expression of
        e@(TextExpression {}) -> e
        e@(VarExpression var) -> if var == alias
                    then fromExpression
                    else e
        e@(CallExpression function args) -> CallExpression function (map rec args)
        e@(NotEqExpression a b) -> NotEqExpression (rec a) (rec b)
        e@(EqExpression a b) -> EqExpression (rec a) (rec b)
        e@(AndExpression a b) -> AndExpression (rec a) (rec b)
        e@(IsExpression a b) -> IsExpression (rec a) (rec b)
        e@(InExpression a b) -> InExpression (rec a) (rec b)
        e@(NotExpression a) -> NotExpression (rec a)
        e@(OrExpression a b) -> OrExpression (rec a) (rec b)
        e@(LessThanExpression a b) -> LessThanExpression (rec a) (rec b)
        e@(LessThanOrEqualToExpression a b) -> LessThanOrEqualToExpression (rec a) (rec b)
        e@(GreaterThanExpression a b) -> GreaterThanExpression (rec a) (rec b)
        e@(GreaterThanOrEqualToExpression a b) -> GreaterThanOrEqualToExpression (rec a) (rec b)
        e@(DoubleExpression {}) -> e
        e@(NumericExpression {}) -> e
        e@(IntExpression {}) -> e
        e@(TypeCastExpression a b) -> (TypeCastExpression (rec a) b)
        e@(SelectExpression Select { columns, from, whereClause, alias }) -> SelectExpression Select { columns = rec <$> columns, from = rec from, whereClause = rec whereClause, alias = alias }
        e@(DotExpression a b) -> DotExpression (rec a) b
        e@(ExistsExpression a) -> ExistsExpression (rec a)
        e@(ConcatenationExpression a b) -> ConcatenationExpression (rec a) (rec b)
        e@(InArrayExpression exprs) -> InArrayExpression (map rec exprs)
        e@(ArrayLiteralExpression exprs) -> ArrayLiteralExpression (map rec exprs)
        e@(VariadicExpression expr) -> VariadicExpression (rec expr)
resolveAlias Nothing fromExpression expression = expression

normalizeSqlType :: PostgresType -> PostgresType
normalizeSqlType (PCustomType customType) = PCustomType (Text.toLower customType)
normalizeSqlType (PGeometryWithModifier modifier) = PGeometryWithModifier (Text.intercalate "," (map (Text.toLower . Text.strip) (Text.splitOn "," modifier)))
normalizeSqlType (PArray elementType) = PArray (normalizeSqlType elementType)
normalizeSqlType PBigserial = PBigInt
normalizeSqlType PSerial = PInt
normalizeSqlType otherwise = otherwise

normalizeNumericLiteral :: Text -> Text
normalizeNumericLiteral value =
    case Read.readMaybe (cs exponentText) :: Maybe Int of
        Nothing -> Text.toLower value
        Just exponent
            | Text.null significantDigits -> "0"
            | otherwise -> sign <> significantDigits <> "e" <> tshow (exponent - Text.length fractionalPart + trailingZeroCount)
    where
        (mantissa, rawExponent) = Text.break (\character -> character == 'e' || character == 'E') value
        exponentText = if Text.null rawExponent then "0" else Text.drop 1 rawExponent
        (sign, unsignedMantissa) = case Text.uncons mantissa of
            Just ('-', rest) -> ("-", rest)
            Just ('+', rest) -> ("", rest)
            _ -> ("", mantissa)
        (integerPart, rawFractionalPart) = Text.break (== '.') unsignedMantissa
        fractionalPart = Text.drop 1 rawFractionalPart
        digits = Text.dropWhile (== '0') (integerPart <> fractionalPart)
        significantDigits = Text.dropWhileEnd (== '0') digits
        trailingZeroCount = Text.length digits - Text.length significantDigits

-- | Returns every migration file created by a generation plan.
migrationPathsFromPlan :: [GeneratorAction] -> [Text]
migrationPathsFromPlan = mapMaybe \case
    CreateFile { filePath } -> Just (osPathToText filePath)
    _ -> Nothing

-- | Returns the last migration file created by a generation plan. For a split
-- plan this is the regular migration, which is the most useful file to open.
migrationPathFromPlan :: [GeneratorAction] -> Text
migrationPathFromPlan plan =
    case reverse (migrationPathsFromPlan plan) of
        path : _ -> path
        [] -> error "Expected the migration plan to create a file"

-- | Removes @ALTER TABLE .. ADD CONSTRAINT .._pkey PRIMARY KEY (id);@ and moves it into the 'primaryKeyConstraint' field of the 'CreateTable'  statement
--
-- pg_dump dumps a table like this:
--
-- > CREATE TABLE a (
-- >     id uuid DEFAULT uuid_generate_v4() NOT NULL
-- > );
-- >
-- > ALTER TABLE a ADD CONSTRAINT users_pkey PRIMARY KEY (id);
--
-- This function basically removes the @ALTER TABLE@ statements and moves the primary key directly into the @CREATE TABLE@ statement:
--
-- > CREATE TABLE a (
-- >     id uuid DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
-- > );
--
normalizePrimaryKeys :: [Statement] -> [Statement]
normalizePrimaryKeys statements = reverse $ normalizePrimaryKeys' [] statements
    where
        normalizePrimaryKeys' normalizedStatements ((AddConstraint { tableName, constraint = AlterTableAddPrimaryKey { primaryKeyConstraint } }):rest) =
            normalizePrimaryKeys'
                (normalizedStatements
                    |> map \case
                        StatementCreateTable { unsafeGetCreateTable = table@(CreateTable { name }) } | name == tableName -> StatementCreateTable { unsafeGetCreateTable = addPK primaryKeyConstraint table }
                        otherwise -> otherwise
                )
                (rest)
        normalizePrimaryKeys' normalizedStatements (statement:rest) = normalizePrimaryKeys' (statement:normalizedStatements) rest
        normalizePrimaryKeys' normalizedStatements [] = normalizedStatements

        addPK :: PrimaryKeyConstraint -> CreateTable -> CreateTable
        addPK PrimaryKeyConstraint { primaryKeyColumnNames } table@(CreateTable { primaryKeyConstraint = PrimaryKeyConstraint { primaryKeyColumnNames = existingPKs } }) = table { primaryKeyConstraint = PrimaryKeyConstraint { primaryKeyColumnNames = existingPKs <> primaryKeyColumnNames } }


-- | Removes @DROP INDEX ..@ statements and other that appear after a @DROP TABLE@ statement. The @DROP TABLE ..@ statement
-- itself already removes indexes and foreigns keys on that table. So an @DROP INDEX ..@ would then fail.
--
-- Shrinks a sequence like this:
--
-- > DROP TABLE a;
-- > DROP INDEX some_index_on_table_a;
-- > ALTER TABLE a DROP CONSTRAINT some_constraint_on_table_a;
--
-- Into this:
--
-- > DROP TABLE a;
--
removeImplicitDeletions :: [Statement] -> [Statement] -> [Statement]
removeImplicitDeletions actualSchema (statement@dropStatement:rest) | isDropStatement dropStatement = dependentDrops <> [statement] <> removeImplicitDeletions actualSchema filteredRest
    where
        dependentDrops = filter isDependentDrop rest
        filteredRest = filter (\candidate -> candidate `notElem` dependentDrops && isImplicitlyDeleted candidate) rest
        isDependentDrop candidate = case dropColumnName of
            Nothing -> isDependentTriggerDrop candidate || isReferencingForeignKeyDrop candidate
            Just _ -> isDependentColumnDrop candidate
        isDependentTriggerDrop DropTrigger { name, tableName }
            | DropTable {} <- dropStatement = any (\case
                CreateConstraintTrigger { name = triggerName, tableName = triggerTableName, referencedTableName = Just referencedTableName } ->
                    triggerName == name && triggerTableName == tableName && referencedTableName == dropTableName
                _ -> False) actualSchema
        isDependentTriggerDrop _ = False
        isReferencingForeignKeyDrop DropConstraint { tableName, constraintName } = any (\case
                AddConstraint { tableName = actualTableName, constraint }
                    | actualTableName == tableName
                    , actualTableName /= dropTableName
                    , constraint.name == Just constraintName -> foreignKeyReferencesDroppedTable constraint
                _ -> False) actualSchema
        isReferencingForeignKeyDrop _ = False
        foreignKeyReferencesDroppedTable ForeignKeyConstraint { referenceTable } = referenceTable == dropTableName
        foreignKeyReferencesDroppedTable CompositeForeignKeyConstraint { referenceTable } = referenceTable == dropTableName
        foreignKeyReferencesDroppedTable _ = False
        isDependentColumnDrop DropTrigger { name, tableName } = tableName == dropTableName || any (\case
                CreateConstraintTrigger { name = triggerName, tableName = triggerTableName, referencedTableName = Just referencedTableName } ->
                    triggerName == name && triggerTableName == tableName && referencedTableName == dropTableName
                _ -> False) actualSchema
        isDependentColumnDrop DropPolicy { tableName } = tableName == dropTableName
        isDependentColumnDrop DropConstraint { tableName, constraintName } = any (\case
                AddConstraint { tableName = actualTableName, constraint }
                    | actualTableName == tableName
                    , constraint.name == Just constraintName -> foreignKeyReferencesDroppedColumn constraint
                _ -> False) actualSchema
        isDependentColumnDrop _ = False
        foreignKeyReferencesDroppedColumn ForeignKeyConstraint { referenceTable, referenceColumn }
            | Just columnName <- dropColumnName = referenceTable == dropTableName && maybe True (== columnName) referenceColumn
        foreignKeyReferencesDroppedColumn CompositeForeignKeyConstraint { referenceTable, referenceColumns }
            | Just columnName <- dropColumnName = referenceTable == dropTableName && (null referenceColumns || columnName `elem` referenceColumns)
        foreignKeyReferencesDroppedColumn _ = False
        isImplicitlyDeleted (DropIndex { indexName }) = case findIndexByName indexName of
                Just CreateIndex { tableName = indexTableName, columns = indexColumns } -> indexTableName /= dropTableName && (
                        case dropColumnName of
                            Just dropColumnName -> indexColumns
                                    |> find (\IndexColumn { column } -> column == VarExpression dropColumnName)
                                    |> isNothing
                            Nothing -> True
                    )
                Just _ -> True  -- Not a CreateIndex, keep it
                Nothing -> True
        isImplicitlyDeleted (DropConstraint { tableName = constraintTableName }) = constraintTableName /= dropTableName
        isImplicitlyDeleted (DropPolicy { tableName = policyTableName }) = not (isNothing dropColumnName && policyTableName == dropTableName)
        isImplicitlyDeleted (DropTrigger { tableName = triggerTableName }) = not (isNothing dropColumnName && triggerTableName == dropTableName)
        isImplicitlyDeleted (NoForceRowLevelSecurity { tableName = forceTableName }) = not (isNothing dropColumnName && forceTableName == dropTableName)
        isImplicitlyDeleted otherwise = True

        findIndexByName :: Text -> Maybe Statement
        findIndexByName name = find (isIndex name) actualSchema

        isIndex :: Text -> Statement -> Bool
        isIndex name CreateIndex { indexName } = indexName == name
        isIndex _    _                         = False

        isDropStatement DropTable {} = True
        isDropStatement DropColumn {} = True
        isDropStatement _ = False

        (dropTableName, dropColumnName) = case dropStatement of
            DropTable { tableName } -> (tableName, Nothing)
            DropColumn { tableName, columnName } -> (tableName, Just columnName)
            _ -> error "removeImplicitDeletions: unexpected statement type"  -- Guard ensures only DropTable/DropColumn reach here
removeImplicitDeletions actualSchema (statement:rest) = statement:(removeImplicitDeletions actualSchema rest)
removeImplicitDeletions actualSchema [] = []

-- | Moves statements that add enum values outside the database transaction
--
-- When IHP generates a migration that contains a statement like this:
--
-- > ALTER TYPE my_enum ADD VALUE 'some_value';
--
-- the migration will fail with this error:
--
-- > Query (89.238182ms): "BEGIN" ()
-- > migrate: SqlError {sqlState = "25001", sqlExecStatus = FatalError, sqlErrorMsg = "ALTER TYPE ... ADD cannot run inside a transaction block", sqlErrorDetail = "", sqlErrorHint = ""}
--
-- This function moves the @ADD VALUE@ statement outside the main database transaction:
--
-- > COMMIT; -- Commit the transaction previously started by IHP
-- > ALTER TYPE my_enum ADD VALUE 'some_value';
-- > BEGIN; -- Restart the connection as IHP will also try to run it's own COMMIT
--
disableTransactionWhileAddingEnumValues :: [Statement] -> [Statement]
disableTransactionWhileAddingEnumValues statements =
        if isEmpty addEnumValueStatements
            then otherStatements
            else [Comment " Commit the transaction previously started by IHP", Commit] <> (map enableIfNotExists addEnumValueStatements) <> [Comment " Restart the connection as IHP will also try to run it's own COMMIT", Begin] <> otherStatements
    where
        (addEnumValueStatements, otherStatements) = partition isAddEnumValueStatement statements

        isAddEnumValueStatement AddValueToEnumType {} = True
        isAddEnumValueStatement otherwise = False

        enableIfNotExists statement@(AddValueToEnumType { .. }) = statement { ifNotExists = True }
        enableIfNotExists otherwise = otherwise

normalizeIndexType :: Maybe IndexType -> Maybe IndexType
normalizeIndexType (Just Btree) = Nothing
normalizeIndexType indexType = indexType

normalizeIndexColumn :: IndexColumn -> IndexColumn
normalizeIndexColumn IndexColumn { column, columnOperatorClass, columnOrder } =
    IndexColumn
        { column = normalizeExpression column
        , columnOperatorClass
        , columnOrder = normalizeIndexColumnOrder columnOrder
        }

normalizeIndexColumnOrder :: [IndexColumnOrder] -> [IndexColumnOrder]
normalizeIndexColumnOrder columnOrder = columnOrder |> filter (/=Asc)

normalizeNewLines :: Text -> Text
normalizeNewLines text =
    text
    |> Text.replace "\r\n" "\n"
    |> Text.replace "\r" "\n"


removeIndentation :: Text -> Text
removeIndentation text =
        lines
        |> map (\line -> if line /= "BEGIN"
                then Text.drop spacesToDrop line
                else line)
        |> Text.unlines
        |> Text.dropAround (\c -> c == '\n')
    where
        lines :: [Text]
        lines = text
                |> Text.lines
        spaces :: [Int]
        spaces = lines
                |> filter (\line -> line /= "" && line /= "BEGIN")
                |> map (\line -> Text.length (Text.takeWhile Char.isSpace line))
        spacesToDrop = spaces |> minimum

-- | Postgres truncates identifiers longer than 63 characters.
--
-- This function truncates a Text to 63 chars max. This way we avoid unnecssary changes in the generated migrations.
truncateIdentifier :: Text -> Text
truncateIdentifier identifier =
    if Text.length identifier > 63
        then Text.take 63 identifier
        else identifier
