# Generated by pip2nix 0.7.0.dev1
# See https://github.com/johbo/pip2nix

{
  "nameparser" = super.buildPythonPackage {
    name = "nameparser-0.5.4";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/cc/04/c89cc89f9450953ff52b8cc86c49ede75466205c282ecd1ba1fcb2051aa4/nameparser-0.5.4.tar.gz";
      sha256 = "18dcv4zlflcf0519hmy6akqbrzqxbsmbsr11hgc2j57dmblbpdwx";
    };
  };
  nltk = super.buildPythonPackage {
    name = "nltk-3.2.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/cc/87/76e691bbf1759ad6af5831649aae6a8d2fa184a1bcc71018ca6300399e5f/nltk-3.2.5.tar.gz";
      sha256 = "0d28rfnvxlxi7cq0zzcpcln3c6l1f2kipmgbpcab6gcq3nbzjq96";
    };
  };
  six = super.buildPythonPackage {
    name = "six-1.11.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  textblob = super.buildPythonPackage {
    name = "textblob-0.14.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [nltk];
    src = fetchurl {
      url = "https://pypi.python.org/packages/79/c6/60c9a28cb43d64f486c6d448dd1bd66ae6b0f0d274a71abc2149ffd0e6ae/textblob-0.14.0.tar.gz";
      sha256 = "022z71xnlzzhllpnv90z7avy82vd3241pdv0nisbqbn0fvz32qy6";
    };
  };
  textblob-de = super.buildPythonPackage {
    name = "textblob-de-0.4.2";
    buildInputs = with self; [nose];
    doCheck = false;
    propagatedBuildInputs = with self; [textblob];
    src = fetchurl {
      url = "https://pypi.python.org/packages/3f/5d/785a5cdb0e0f86da18144dc1e3636f44f6ea04424872bea7c16856b9362a/textblob-de-0.4.2.tar.gz";
      sha256 = "1vnawcwzygsvxwac2csq81i0sck6mi1ynllg7zzmy57jdfq9d45r";
    };
  };
}
