name: Check PR compiles without errors
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/093f236f30c3b82205355806043263a8d636f8c2.tar.gz
    - uses: cachix/cachix-action@v12
      with:
        name: digitallyinduced
        skipPush: true

    - run: |
          cd $GITHUB_WORKSPACE
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
          nix-shell --run "cabal build --flag FastBuild"
