name: "Tests"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/093f236f30c3b82205355806043263a8d636f8c2.tar.gz
    - uses: cachix/cachix-action@v12
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "runghc $(make -f lib/IHP/Makefile.dist print-ghc-extensions) -iIDE Test/Main.hs"
