{-# LANGUAGE FlexibleInstances, UndecidableInstances #-}
{-|
Module: IHP.Hasql.FromRow
Description: Typeclass for decoding hasql result rows
Copyright: (c) digitally induced GmbH, 2025

This module provides 'FromRowHasql', a typeclass parallel to postgresql-simple's 'FromRow',
for decoding database rows using hasql's more efficient prepared statement approach.

Instances are generated by the SchemaCompiler with explicit inline decoders in idiomatic
hasql applicative style.

Also provides parser functions used by the generated decoders for custom PostgreSQL types.
-}
module IHP.Hasql.FromRow
( FromRowHasql (..)
, HasqlDecodeValue (..)
, HasqlDecodeColumn (..)
) where

import Prelude
import Data.ByteString (ByteString)
import Data.Text (Text)
import Data.UUID (UUID)
import Data.Time.Clock (UTCTime, DiffTime)
import Data.Time.Calendar (Day)
import Data.Time.LocalTime (TimeOfDay)
import qualified Hasql.Decoders as Decoders
import qualified Hasql.Mapping.IsScalar as Mapping
import Data.Int (Int16, Int32, Int64)
import Data.Scientific (Scientific)
import qualified Data.Aeson as Aeson
import qualified Database.PostgreSQL.Simple.Types as PG
import IHP.ModelSupport.Types (LabeledData(..), Id'(..), PrimaryKey)

-- | Typeclass for types that can be decoded from a hasql result row
--
-- This is the hasql equivalent of postgresql-simple's 'FromRow' class.
-- The SchemaCompiler generates instances for all model types using idiomatic
-- hasql applicative style with explicit inline decoders.
class FromRowHasql a where
    -- | Decoder for a single row
    hasqlRowDecoder :: Decoders.Row a

-- | Typeclass mapping Haskell scalar types to hasql value decoders
class HasqlDecodeValue a where
    hasqlDecodeValue :: Decoders.Value a

instance HasqlDecodeValue Int16 where hasqlDecodeValue = Decoders.int2
instance HasqlDecodeValue Int32 where hasqlDecodeValue = Decoders.int4
instance HasqlDecodeValue Int64 where hasqlDecodeValue = Decoders.int8
instance HasqlDecodeValue Int where hasqlDecodeValue = fromIntegral <$> Decoders.int8
instance HasqlDecodeValue Bool where hasqlDecodeValue = Decoders.bool
instance HasqlDecodeValue Text where hasqlDecodeValue = Decoders.text
instance HasqlDecodeValue ByteString where hasqlDecodeValue = Decoders.bytea
instance HasqlDecodeValue UUID where hasqlDecodeValue = Decoders.uuid
instance HasqlDecodeValue UTCTime where hasqlDecodeValue = Decoders.timestamptz
instance HasqlDecodeValue Day where hasqlDecodeValue = Decoders.date
instance HasqlDecodeValue TimeOfDay where hasqlDecodeValue = Decoders.time
instance HasqlDecodeValue DiffTime where hasqlDecodeValue = Decoders.interval
instance HasqlDecodeValue Scientific where hasqlDecodeValue = Decoders.numeric
instance HasqlDecodeValue Double where hasqlDecodeValue = Decoders.float8
instance HasqlDecodeValue Float where hasqlDecodeValue = Decoders.float4
instance HasqlDecodeValue Aeson.Value where hasqlDecodeValue = Decoders.jsonb
instance Mapping.IsScalar (PrimaryKey table) => HasqlDecodeValue (Id' table) where hasqlDecodeValue = Id <$> Mapping.decoder

-- | Typeclass for building column-level row decoders, handling nullable/non-nullable
class HasqlDecodeColumn a where
    hasqlColumnDecoder :: Decoders.Row a

instance {-# OVERLAPPABLE #-} HasqlDecodeValue a => HasqlDecodeColumn a where
    hasqlColumnDecoder = Decoders.column (Decoders.nonNullable hasqlDecodeValue)

instance {-# OVERLAPPING #-} HasqlDecodeValue a => HasqlDecodeColumn (Maybe a) where
    hasqlColumnDecoder = Decoders.column (Decoders.nullable hasqlDecodeValue)

-- FromRowHasql instances for PG.Only and tuples (used by sqlQuery callers like fetchCount, fetchExists)

instance HasqlDecodeColumn a => FromRowHasql (PG.Only a) where
    hasqlRowDecoder = PG.Only <$> hasqlColumnDecoder

instance (HasqlDecodeColumn a, HasqlDecodeColumn b) => FromRowHasql (a, b) where
    hasqlRowDecoder = (,) <$> hasqlColumnDecoder <*> hasqlColumnDecoder

instance (HasqlDecodeColumn a, HasqlDecodeColumn b, HasqlDecodeColumn c) => FromRowHasql (a, b, c) where
    hasqlRowDecoder = (,,) <$> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder

instance (HasqlDecodeColumn a, HasqlDecodeColumn b, HasqlDecodeColumn c, HasqlDecodeColumn d) => FromRowHasql (a, b, c, d) where
    hasqlRowDecoder = (,,,) <$> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder

instance (HasqlDecodeColumn a, HasqlDecodeColumn b, HasqlDecodeColumn c, HasqlDecodeColumn d, HasqlDecodeColumn e) => FromRowHasql (a, b, c, d, e) where
    hasqlRowDecoder = (,,,,) <$> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder <*> hasqlColumnDecoder

instance (HasqlDecodeColumn label, FromRowHasql a) => FromRowHasql (LabeledData label a) where
    hasqlRowDecoder = LabeledData <$> hasqlColumnDecoder <*> hasqlRowDecoder
