#!/bin/bash -e

if [ $# -eq 0 ]; then
  echo "Usage: $0 <script-path>"
  echo "Example: $0 Application/Script/HelloWorldToAllUsers.hs"  
  exit 1
fi

TASK_PATH="$1"
TASK_MODULE="$TASK_PATH"
TASK_MODULE="''${TASK_MODULE#./}"   # drop leading ./
TASK_MODULE="''${TASK_MODULE%.hs}"  # drop .hs
TASK_MODULE="''${TASK_MODULE%.lhs}" # drop .lhs (if ever used)
TASK_MODULE="''${TASK_MODULE////.}" # convert / -> . (path to module)

GHCI_SCRIPT="$(mktemp -t runscript.XXXXXX)"
trap 'rm -f "$GHCI_SCRIPT"' EXIT
  {
  echo ":script ${ihp}/ihp-ide/data/lib/IHP/applicationGhciConfig"
  echo "import IHP.ScriptSupport"
  echo ":set -i." 
  echo ":l Config/Config.hs $TASK_PATH"
  echo "import qualified $TASK_MODULE  as Script"              
  echo "IHP.ScriptSupport.runScript config Script.run"
  echo ":quit"
  } > "$GHCI_SCRIPT"
ghci -package-env - -threaded -fomit-interface-pragmas +RTS -A128m -RTS < "$GHCI_SCRIPT"
