CSS_FILES += src/Foundation/static/vendor/bootstrap.min.css
CSS_FILES += src/Foundation/static/vendor/flatpickr.min.css

JS_FILES += src/Foundation/static/vendor/jquery-3.2.1.slim.min.js
JS_FILES += src/Foundation/static/vendor/timeago.js
JS_FILES += src/Foundation/static/vendor/popper.min.js
JS_FILES += src/Foundation/static/vendor/bootstrap.min.js
JS_FILES += src/Foundation/static/vendor/flatpickr.js
JS_FILES += src/Foundation/static/helpers.js
JS_FILES += src/Foundation/static/vendor/morphdom-umd.min.js
JS_FILES += src/Foundation/static/vendor/turbolinks.js
JS_FILES += src/Foundation/static/vendor/turbolinksInstantClick.js
JS_FILES += src/Foundation/static/vendor/turbolinksMorphdom.js

include src/Foundation/Makefile.dist