name: Linux Build Test
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - uses: cachix/cachix-action@v6
      with:
        name: digitallyinduced
        skipPush: true

    - run: |
          cd $GITHUB_WORKSPACE
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
          nix-shell NixSupport/shell.nix --run "cabal build"
