name: Check PR compiles without errors
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ARM64
    steps:
    - uses: actions/checkout@v3
    - run: |
          cd $GITHUB_WORKSPACE
          nix develop --impure --command fastbuild
