name: Check PR compiles without errors
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ARM64
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/a95ed9fe764c3ba2bf2d2fa223012c379cd6b32e.tar.gz
      if: matrix.os != 'ARM64'
    - uses: cachix/cachix-action@v12
      with:
        name: digitallyinduced
        skipPush: true
      if: matrix.os != 'ARM64'
    - run: |
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
      if: matrix.os != 'ARM64'
    - run: |
          cd $GITHUB_WORKSPACE
          nix develop --impure --command fastbuild
