name: "nix flake check --impure"
on:
  pull_request:
    branches: [master]
  push:
    branches: 'master'

permissions:
  contents: read

jobs:
  nix-flake-check:
    runs-on: ARM64
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false
    - name: Free disk space on the self-hosted runner
      run: nix store gc --max 30G
    - run: nix flake check --impure --override-input ihp-boilerplate/ihp "github:${{ github.event.repository.full_name }}/${{ github.sha }}" -L